# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_bannercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/media/course/resource/2018/11/videoplayback.mp4', verbose_name='访问地址'),
        ),
    ]
